config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  root "jobs#index"
end

app/models/job.rb
class Job < ActiveRecord::Base

  has_many :tasks, :dependent => :destroy
  accepts_nested_attributes_for :tasks, :reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :job
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :load_job , only: [:show,:edit,:update]
  helper :jobs

  def index
    @jobs = Job.all
  end
  def show
  end
  def new
    @job = Job.new
  end
  def edit
  end
  def create
    @job = Job.new(job_params)
    if(@job.save)
      redirect_to job_url(@job), notice: 'Job was successfully created'
    else
      render :new
    end
  end
  def update
    if(@job.update(job_params))
      redirect_to job_url(@job), notice: 'Job was successfully updated'
    else
      render :edit
    end
  end

  private
  def load_job
    @job = Job.find(params[:id])
  end
  def job_params
    params.require(:job).permit(:id,:title, :tasks_attributes => [:id, :name,:_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
  def new_fields_template(f,association,options={})
    options[:object] ||= f.object.class.reflect_on_association(association).klass.new
    options[:partial] ||= association.to_s.singularize+"_fields"
    options[:template] ||= association.to_s+"_fields"
    options[:f] ||= :f

   tmpl = content_tag(:div,:id =>"#{options[:template]}") do
      tmpl = f.fields_for(association,options[:object], :child_index => "new_#{association}") do |b|
        render(:partial=>options[:partial],:locals =>{:f => b})
      end
    end
    tmpl = tmpl.gsub /(?<!\n)\n(?!\n)/, ' '
    return "<script> var #{options[:template]} = '#{tmpl.to_s}' </script>".html_safe
  end
  def add_child_button(name, association,target)
    content_tag(:spam,"<span>#{name}</span>".html_safe,
      :class => "add_child",
      :style => "cursor:pointer; border:1px solid #777;",
      :"data-association" => association,
      :target => target)
  end
  def remove_child_button(name)
    content_tag(:div,"<span>Remove</span>".html_safe,
      :style => "cursor:pointer; border:1px solid #777; display:inline-block; width: 60px;",
      :class => "remove_child")
  end
end

app/views/jobs/_form.html.erb
<%= form_for @job do |f| %>
  <% if @job.errors.any? %>
    <% @job.errors.full_messages.each do |message| %>
            <br/><span><%= message %></span>
      <% end %>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title %> <br/>

  <div>
    <%= add_child_button "New Task",:tasks,"#tasks" %>
    <%= new_fields_template f, :tasks %>
  </div>

  <div id="tasks" style="border:1px solid #777;">
      <%= f.fields_for :tasks do |builder| %>
        <div>
        <%= render "task_fields", :f => builder %>
      </div>
      <% end %>
  </div>

  <%= f.submit "Save" %>
<%end %>
<%= link_to "Back", jobs_path%>

app/views/jobs/_task_fields.html.erb
<%= f.hidden_field :_destroy, :class => 'removable' %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= remove_child_button "Remove"%>

app/views/jobs/edit.html.erb
<h2>Edit Job</h2>
<%= render "form"%>

app/views/jobs/index.html.erb
<%= link_to "New Job", new_job_path%>
<table>
<thead>
  <tr><th>ID</th><th>Title</th><th>manage</th></tr>
</thead>
<tbody>
<% @jobs.each do |job| %>
    <tr>
      <td><%= job.id %></td>
      <td><%= link_to job.title, job_path(job) %></td>
      <td><%= link_to "Edit", edit_job_path(job) %>
          <%= link_to "Delete", job_path(job), method: :delete %>
      </td>
    </tr>
<%end%>
</tbody>
</table>

app/views/jobs/new.html.erb
<h2>New Job</h2>
<%= render "form"%>

app/views/jobs/show.html.erb
<h2>Job <%= @job.title%></h2>
<span><%=notice%></span><br/>
<%= link_to "Back", jobs_path%>
<%= link_to "Edit", edit_job_path(@job)%>
<%= link_to "Delete", job_path(@job), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Example</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>